<?php

namespace Database\Seeders;

use App\Models\Region;
use Illuminate\Database\Seeder;

class PhoneRegionSeeder extends Seeder
{
    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $regionList = [
            ['region' => '10',
                'description' => 'Всеукраїнські гарячі лінії'],
            ['region' => '31',
                'description' => 'Закарпатська область'],
            ['region' => '32',
                'description' => 'Львівська область'],
            ['region' => '33',
                'description' => 'Волинська область'],
            ['region' => '34',
                'description' => 'Івано-Франківська область'],
            ['region' => '35',
                'description' => 'Тернопільська область'],
            ['region' => '36',
                'description' => 'Рівненська область'],
            ['region' => '37',
                'description' => 'Чернівецька область'],
            ['region' => '38',
                'description' => 'Хмельницька область'],
            ['region' => '41',
                'description' => 'Житомирська область'],
            ['region' => '43',
                'description' => 'Вінницька область'],
            ['region' => '44',
                'description' => 'Київ'],
            ['region' => '45',
                'description' => 'Київська область'],
            ['region' => '46',
                'description' => 'Чернігівська область'],
            ['region' => '47',
                'description' => 'Черкаська область'],
            ['region' => '48',
                'description' => 'Одеська область'],
            ['region' => '49',
                'description' => 'Станції супутникової телефонії'],
            ['region' => '50',
                'description' => 'Vodafone'],
            ['region' => '51',
                'description' => 'Миколаївська область'],
            ['region' => '52',
                'description' => 'Кіровоградська область'],
            ['region' => '53',
                'description' => 'Полтавська область'],
            ['region' => '54',
                'description' => 'Сумська область'],
            ['region' => '55',
                'description' => 'Херсонська область'],
            ['region' => '56',
                'description' => 'Дніпропетровська область'],
            ['region' => '57',
                'description' => 'Харківська область'],
            ['region' => '61',
                'description' => 'Запорізька область'],
            ['region' => '62',
                'description' => 'Донецька область'],
            ['region' => '63',
                'description' => 'LifeCell'],
            ['region' => '64',
                'description' => 'Луганська область'],
            ['region' => '65',
                'description' => 'АР Крим'],
            ['region' => '66',
                'description' => 'Vodafone'],
            ['region' => '67',
                'description' => 'Київстар'],
            ['region' => '68',
                'description' => 'Київстар'],
            ['region' => '69',
                'description' => 'Севастополь'],
            ['region' => '70',
                'description' => 'Укртелеком'],
            ['region' => '71',
                'description' => 'Фенікс'],
            ['region' => '72',
                'description' => 'Лугаком'],
            ['region' => '73',
                'description' => 'LifeCell'],
            ['region' => '80',
                'description' => 'Безкоштовні гарячі лінії'],
            ['region' => '89',
                'description' => 'SIP'],
            ['region' => '90',
                'description' => 'Укртелеком'],
            ['region' => '91',
                'description' => '3Mob'],
            ['region' => '92',
                'description' => 'PEOPLEnet'],
            ['region' => '93',
                'description' => 'LifeCell'],
            ['region' => '94',
                'description' => 'Інтертелеком'],
            ['region' => '95',
                'description' => 'Vodafone'],
            ['region' => '96',
                'description' => 'Київстар'],
            ['region' => '97',
                'description' => 'Київстар'],
            ['region' => '98',
                'description' => 'Київстар'],
            ['region' => '99',
                'description' => 'Vodafone'],
        ];

        Region::query()->insert($regionList);
    }
}
